steps:
  # Utilisation d'une version spécifique pour éviter l'erreur de "manifest unknown"
  - name: 'gcr.io/cloud-builders/firebase:v1'
    args: ['deploy', '--project', '$PROJECT_ID', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY
