steps:
  # Utilisation de l'image officielle Firebase 2026
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args: ['deploy', '--project', '$PROJECT_ID', '--only', 'hosting']

options:
  logging: CLOUD_LOGGING_ONLY
